#!/usr/bin/env python3
"""Run wyoming-whisperkit using the local .venv."""
import subprocess
import sys
import venv
from pathlib import Path

_DIR         = Path(__file__).parent
_PROGRAM_DIR = _DIR.parent
_VENV_DIR    = _PROGRAM_DIR / ".venv"

context = venv.EnvBuilder().ensure_directories(_VENV_DIR)
subprocess.check_call([context.env_exe, "-m", "wyoming_whisperkit"] + sys.argv[1:])
